# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mol',
            name='parentid_mol',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
