# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_mol_parentid_mol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mol',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mol',
            name='submitted_date',
        ),
    ]
